<% if resource.errors.any? then %>
  <div id="error_explanation">
    <h2 style='color: red; padding-top: 30px;'>登録失敗！！（エラー：<%= resource.errors.count %>件発生）
      <%#= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <% dic = { first_name: 'ユーザーネーム（名）',
    last_name: 'ユーザーネーム（姓）',
    first_name_kana: 'ユーザーネーム（カナ名）',
    last_name_kana: 'ユーザーネーム（カナ姓）',
    postal_code: '郵便番号',
    address: '住所',
    phone_number: '電話番号',
    email: 'メールアドレス',
    password: 'パスワード'
  } %>
    <ul>
      <li style='padding: 10px 0 5px;'><b><%= 'エラー発生項目'.center( 21, ?　 ) %></b><%='エラー内容'.center( 13, ?　 ) %></li>
      <% resource.errors.each do |key, message| %>
      <% if dic.has_key?(key) then %>
      <li style='padding: 5px 0;'><b style='color: red;'><%= dic[key].center( 21, ?　 ) %></b>　の項目に不備があります。</li>
      <% else %>
      <li style='padding: 5px 0;'><b style='color: red;'><%= key.to_s.center( 21, ?　 ) %></b>　の項目に不備があります。</li>
      <% end %>
      <% end %>
    </ul>
  </div>
  <% end %>
